/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/renderer/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'void-base': 'var(--base, #0A0A0D)',
        'void-surface': 'var(--surface, #111115)',
        'void-elevated': 'var(--elevated, #141418)',
        'void-input': 'var(--input, #0E0E12)',
        'void-border': 'var(--border, #2A2A30)',
        'void-border-hover': '#3A3A42',
        accent: 'var(--accent, #F97316)',
        'accent-hover': '#FB923C',
        'accent-dim': 'rgba(249, 115, 22, 0.25)',
        'accent-glow': 'rgba(249, 115, 22, 0.08)',
        'accent-glow-border': 'rgba(249, 115, 22, 0.12)',
        'status-online': '#28C840',
        'status-warning': '#FEBC2E',
        'status-error': '#FF5F57',
        'status-info': '#5B9BD5',
        'status-ai': '#C586C0',
        'void-text': 'var(--text, #E8E6E0)',
        'void-text-muted': 'var(--muted, #888888)',
        'void-text-dim': 'var(--dim, #555555)',
        'void-text-ghost': 'var(--ghost, #444444)',
        'void-text-faint': '#333333',
        // Glow variants
        'danger-glow': 'rgba(255, 95, 87, 0.03)',
        'danger-glow-border': 'rgba(255, 95, 87, 0.15)',
        'nlp-glow': 'rgba(197, 134, 192, 0.05)',
        'nlp-glow-border': 'rgba(197, 134, 192, 0.15)',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'SF Mono', 'Fira Code', 'monospace'],
        sans: ['DM Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        'xs': ['11px', '16px'],
        'sm': ['12px', '18px'],
        'base': ['13px', '20px'],
        'lg': ['14px', '22px'],
        'xl': ['16px', '24px'],
        '2xl': ['22px', '28px'],
      },
      borderRadius: {
        'void': '6px',
        'void-lg': '8px',
        'void-xl': '10px',
        'void-2xl': '12px',
      },
      animation: {
        'slide-in-right': 'slideInRight 250ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1))',
        'slide-in-left': 'slideInLeft 250ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1))',
        'palette-in': 'paletteIn 200ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1))',
        'ai-suggest-in': 'aiSuggestIn 250ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1)) 300ms both',
        'danger-shake': 'dangerShake 300ms ease',
        'note-in': 'noteIn 250ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1))',
        'tab-in': 'tabIn 200ms var(--ease-enter, cubic-bezier(0, 0, 0.2, 1))',
        'rec-pulse': 'recPulse 1.5s infinite',
        'reconnect-pulse': 'reconnectPulse 1.5s infinite',
        'ai-pulse': 'aiPulse 2s infinite',
      },
    },
  },
  plugins: [],
};
